---
title: "Noela's Website"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About
My name is Noela Tenku and I am an aspiring Data Scientist. Currently, I'm taking the Cloud-Based Data Science course on Learnpub. By the end of 2021, my goal is to be proficient enough to work on data analysis problems in R and data visualization in Tableau.

I have worked as an IT consultant for a Non-profit organization where I deployed and customized different open source solutions for a community project. There, I got to experience the importance of proper data management from collection till making decisions based on the results of the data analyst. This gave more reasons to want to pursue the career of a data analyst.

## Interests
-Data visualization
-IT support
-Community building
-Project Management

## Projects
-Building my personal website

## Profiles
-[LinkedIn](http://www.linkedin.com/in/noela-tenku)
-[Github](https://github.com/Noela-T)

## Contact
[tenkunoela@gmail.com](mailto:tenkunoela@gmail.com)